### ISSUE TITLE
frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'

### ISSUE THREAD

**Issue by AnxiangLemon** [lasting-yang/frida-qbdi-tracer#1]
![image](https://user-images.githubusercontent.com/38586233/226123915-28df36e3-ea2f-4215-9ef3-a2b794e97f55.png)

PS H:\IDA\frida-qbdi-tracer> Python .\start_trace.py

> build
> frida-compile agent.js -o _agent.js -c -S

Traceback (most recent call last):
  File "H:\IDA\frida-qbdi-tracer\start_trace.py", line 40, in <module>
    script = session.create_script(read_agent_js_source())
  File "D:\Python310\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "D:\Python310\lib\site-packages\frida\core.py", line 262, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.InvalidArgumentError: could not load module 'QBDI/frida-qbdi.js'
PS H:\IDA\frida-qbdi-tracer> frida --version
15.1.17
PS H:\IDA\frida-qbdi-tracer> node --version
v18.4.0
PS H:\IDA\frida-qbdi-tracer> python --version
Python 3.10.4
PS H:\IDA\frida-qbdi-tracer>

**Comment by AnxiangLemon** [comment]
不要用win

**Comment by FBLeee** [comment]
> 不要用win

我用mac也不行，还是报这个错误，请问你用的什么系统？
